# Checker for the cases generated by G.gen.py

with open("mapping.txt") as h:
    mapping = [*map(int, h.readline().split())]

N = len(mapping)

with open("output_1.txt") as f:
    hashes1 = [*map(lambda l : l.strip(), f.readlines())]

with open("output_2.txt") as g:
    hashes2 = [*map(lambda l : l.strip(), g.readlines())]

acs = 0
was = 0

for i in range(N):
    if hashes1[i] == hashes2[mapping[i]]:
        acs += 1
    else:
        was += 1

print(f"ACs: {acs}, WAs: {was}")
